### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by deavmi** [BradleyChatha/jcli#57]
Not sure when this started happening but maybe when I upgraded my compiler? I am running version `DMD64 D Compiler v2.102.2` of dmd and the version of the package I am using is `DMD64 D Compiler v2.102.2`, could you confirm whether this happens on your machine or not (so I can downgrade my compiler to get stuff working again):

```
deavmi@xps:~/Documents/Projects/t/code$ dub build && ./tlang compile source/tlang/testing/simple_arrays4.t && ./tlang.out 
    Starting Performing "debug" build using /usr/bin/dmd for x86_64.
  Up-to-date gogga 0.1.3: target for configuration [library] is up to date.
    Building jcli:core 0.25.0-beta.1: building configuration [library]
../../../../.dub/packages/jcli-0.25.0-beta.1/jcli/subprojects/core/source/jcli/core/flags.d(92,5): Error: enum member `jcli.core.flags.ArgFlags._multipleBit` circular reference to `enum` member
../../../../.dub/packages/jcli-0.25.0-beta.1/jcli/subprojects/core/source/jcli/core/flags.d(101,5): Error: enum member `jcli.core.flags.ArgFlags._countBit` circular reference to `enum` member
../../../../.dub/packages/jcli-0.25.0-beta.1/jcli/subprojects/core/source/jcli/core/flags.d(115,27): Error: struct `jcli.core.flags.IncompatibleWithAnyOf` no size because of forward reference
Error /usr/bin/dmd failed with exit code 1.
```

**Comment by deavmi** [comment]
Seems to work on `dmd-2.099.1-0.fedora.x86_64.rpm` :heavy_check_mark: 
Seems to work on `dmd-2.100.0-0.fedora.x86_64.rpm` :heavy_check_mark: 
Also on `dmd-2.100.2-0.fedora.x86_64.rpm)` :heavy_check_mark: 

And it seems that `dmd-2.101.0-0.fedora.x86_64` is what works and was what I probably was on so I will stick to it :checkered_flag:

**Comment by deavmi** [comment]
I will leave this open for you guys, thought I should bring it up, noticed it whilst working on https://deavmi.assigned.network/git/tlang/tlang/issues/81#issuecomment-969

**Comment by BradleyChatha** [comment]
Yeah I get the same error. Odd.

I'll try to look into it this week for you.

**Comment by BradleyChatha** [comment]
LDC 1.31.0 (despite being based off of dmd 2.101.2) works though :sweat_smile:

Guess I'll also work on a bug report at some point as well; since this might be a regression then.

**Comment by deavmi** [comment]
> Yeah I get the same error. Odd.
> 
> I'll try to look into it this week for you.

Thank you very much! I at least know which version of `dmd` I need but guess it is a good heads up.

**Comment by deavmi** [comment]
Any updates on this?
